export const site = {
  name: "Universal Structural Steel",
  legalName: "Universal Structural Steel Ltd.",
  shortName: "USS",
  tagline: "Concept to Construction",
  description:
    "Universal Structural Steel Ltd. designs, fabricates and erects pre-engineered steel buildings across Bangladesh — industrial, commercial, residential and agro-based structures, delivered from measurement to handover under one accountable team.",
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "https://www.universalsteelbd.com",
  locale: "en_BD",
  founded: "2016",
  email: "universalssltd@gmail.com",
  careersEmail: "careers@universalsteelbd.com",
  phone: "+880 1537-528399",
  phoneHref: "+8801537528399",
  phoneSecondary: "+880 1729-298919",
  phoneSecondaryHref: "+8801729298919",
  address: {
    street: "House 16/6, 2nd Floor, Block B, Babor Road",
    locality: "Mohammadpur, Shyamoli, Dhaka",
    region: "Dhaka Division",
    postalCode: "1207",
    country: "BD",
    countryName: "Bangladesh",
  },
  factory: {
    street: "North Kasor, Square Master Bari",
    locality: "Bhaluka",
    region: "Mymensingh",
    country: "BD",
    countryName: "Bangladesh",
    phone: "+880 1729-298935",
    phoneHref: "+8801729298935",
    email: "universalssltdfac@gmail.com",
  },
  sisterConcerns: [
    {
      name: "Versatile Construction Solutions Ltd.",
      description: "Construction solutions",
      logo: "/images/logos/sister/versatile-construction-solutions-ltd.png",
    },
    {
      name: "Versatile Design Consultants",
      description: "Architectural & design consultancy",
      logo: "/images/logos/sister/versatile-design-consultants.png",
    },
    {
      name: "Universal Energy",
      description: "Empowering a sustainable tomorrow",
      logo: "/images/logos/sister/universal-energy.png",
    },
  ],
  social: {
    linkedin: "https://www.linkedin.com/company/universal-structural-steel",
    x: "https://x.com/universalsteelbd",
    youtube: "https://www.youtube.com/@universalstructuralsteelltd.",
    facebook: "https://www.facebook.com/universalsteelbd",
  },
  ogImage: "/images/hero/og-default.svg",
} as const;
